-- ClinicMaxx schema for Supabase.
-- Paste this whole file into: Supabase dashboard -> SQL Editor -> New query -> Run.
-- Safe to run more than once.

CREATE TABLE IF NOT EXISTS clinic (
  id                     integer PRIMARY KEY CHECK (id = 1),
  name                   text NOT NULL,
  tagline                text NOT NULL DEFAULT '',
  email                  text NOT NULL DEFAULT '',
  phone                  text NOT NULL DEFAULT '',
  website                text NOT NULL DEFAULT '',
  timezone               text NOT NULL DEFAULT 'America/Vancouver',
  currency               text NOT NULL DEFAULT 'CAD',
  booking_lead_hours     integer NOT NULL DEFAULT 2,
  cancellation_hours     integer NOT NULL DEFAULT 24,
  cancellation_fee_cents integer NOT NULL DEFAULT 4000,
  default_tax_bps        integer NOT NULL DEFAULT 0,
  invoice_prefix         text NOT NULL DEFAULT 'CMX',
  next_invoice_seq       integer NOT NULL DEFAULT 1001
);

CREATE TABLE IF NOT EXISTS locations (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        text NOT NULL,
  address     text NOT NULL DEFAULT '',
  city        text NOT NULL DEFAULT '',
  region      text NOT NULL DEFAULT '',
  postal_code text NOT NULL DEFAULT '',
  phone       text NOT NULL DEFAULT '',
  is_active   smallint NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS disciplines (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        text NOT NULL UNIQUE,
  color       text NOT NULL DEFAULT 'teal',
  description text NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS practitioners (
  id             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name     text NOT NULL,
  last_name      text NOT NULL,
  credentials    text NOT NULL DEFAULT '',
  discipline_id  integer NOT NULL REFERENCES disciplines(id),
  email          text NOT NULL DEFAULT '',
  phone          text NOT NULL DEFAULT '',
  bio            text NOT NULL DEFAULT '',
  color          text NOT NULL DEFAULT 'teal',
  role           text NOT NULL DEFAULT 'practitioner',
  location_id    integer REFERENCES locations(id),
  online_booking smallint NOT NULL DEFAULT 1,
  is_active      smallint NOT NULL DEFAULT 1,
  started_on     text NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS availability (
  id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  practitioner_id integer NOT NULL REFERENCES practitioners(id) ON DELETE CASCADE,
  location_id     integer REFERENCES locations(id),
  weekday         integer NOT NULL,
  start_min       integer NOT NULL,
  end_min         integer NOT NULL
);

CREATE TABLE IF NOT EXISTS treatments (
  id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name            text NOT NULL,
  discipline_id   integer NOT NULL REFERENCES disciplines(id),
  duration_min    integer NOT NULL,
  price_cents     integer NOT NULL,
  tax_bps         integer NOT NULL DEFAULT 0,
  description     text NOT NULL DEFAULT '',
  online_bookable smallint NOT NULL DEFAULT 1,
  is_active       smallint NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS practitioner_treatments (
  practitioner_id integer NOT NULL REFERENCES practitioners(id) ON DELETE CASCADE,
  treatment_id    integer NOT NULL REFERENCES treatments(id) ON DELETE CASCADE,
  PRIMARY KEY (practitioner_id, treatment_id)
);

CREATE TABLE IF NOT EXISTS patients (
  id               integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name       text NOT NULL,
  last_name        text NOT NULL,
  preferred_name   text NOT NULL DEFAULT '',
  email            text NOT NULL DEFAULT '',
  phone            text NOT NULL DEFAULT '',
  date_of_birth    text NOT NULL DEFAULT '',
  pronouns         text NOT NULL DEFAULT '',
  address          text NOT NULL DEFAULT '',
  city             text NOT NULL DEFAULT '',
  region           text NOT NULL DEFAULT '',
  postal_code      text NOT NULL DEFAULT '',
  emergency_name   text NOT NULL DEFAULT '',
  emergency_phone  text NOT NULL DEFAULT '',
  occupation       text NOT NULL DEFAULT '',
  referral_source  text NOT NULL DEFAULT '',
  family_doctor    text NOT NULL DEFAULT '',
  alert            text NOT NULL DEFAULT '',
  tags             text NOT NULL DEFAULT '',
  notes            text NOT NULL DEFAULT '',
  intake_completed smallint NOT NULL DEFAULT 0,
  consent_signed   smallint NOT NULL DEFAULT 0,
  is_active        smallint NOT NULL DEFAULT 1,
  created_at       text NOT NULL
);

CREATE TABLE IF NOT EXISTS insurance_policies (
  id               integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id       integer NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
  insurer_name     text NOT NULL,
  plan_type        text NOT NULL DEFAULT 'extended',
  policy_number    text NOT NULL DEFAULT '',
  member_id        text NOT NULL DEFAULT '',
  coverage_percent integer NOT NULL DEFAULT 80,
  annual_max_cents integer NOT NULL DEFAULT 50000,
  used_cents       integer NOT NULL DEFAULT 0,
  visits_allowed   integer NOT NULL DEFAULT 0,
  visits_used      integer NOT NULL DEFAULT 0,
  direct_billing   smallint NOT NULL DEFAULT 1,
  is_primary       smallint NOT NULL DEFAULT 1,
  valid_to         text NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS appointments (
  id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id      integer NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
  practitioner_id integer NOT NULL REFERENCES practitioners(id),
  treatment_id    integer NOT NULL REFERENCES treatments(id),
  location_id     integer REFERENCES locations(id),
  starts_at       text NOT NULL,
  ends_at         text NOT NULL,
  status          text NOT NULL DEFAULT 'booked',
  source          text NOT NULL DEFAULT 'staff',
  is_first_visit  smallint NOT NULL DEFAULT 0,
  notes           text NOT NULL DEFAULT '',
  cancel_reason   text NOT NULL DEFAULT '',
  reminder_sent   smallint NOT NULL DEFAULT 0,
  invoice_id      integer,
  created_at      text NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_appt_start ON appointments(starts_at);
CREATE INDEX IF NOT EXISTS idx_appt_prac  ON appointments(practitioner_id, starts_at);
CREATE INDEX IF NOT EXISTS idx_appt_pat   ON appointments(patient_id, starts_at);

CREATE TABLE IF NOT EXISTS chart_templates (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name          text NOT NULL,
  discipline_id integer REFERENCES disciplines(id),
  kind          text NOT NULL DEFAULT 'soap',
  fields_json   text NOT NULL
);

CREATE TABLE IF NOT EXISTS chart_notes (
  id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id      integer NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
  practitioner_id integer NOT NULL REFERENCES practitioners(id),
  appointment_id  integer REFERENCES appointments(id) ON DELETE SET NULL,
  template_id     integer REFERENCES chart_templates(id),
  title           text NOT NULL,
  body_json       text NOT NULL DEFAULT '{}',
  status          text NOT NULL DEFAULT 'draft',
  signed_at       text NOT NULL DEFAULT '',
  created_at      text NOT NULL,
  updated_at      text NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_note_patient ON chart_notes(patient_id, created_at DESC);

CREATE TABLE IF NOT EXISTS products (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        text NOT NULL,
  sku         text NOT NULL DEFAULT '',
  price_cents integer NOT NULL,
  cost_cents  integer NOT NULL DEFAULT 0,
  stock       integer NOT NULL DEFAULT 0,
  tax_bps     integer NOT NULL DEFAULT 1200,
  is_active   smallint NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS invoices (
  id             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  number         text NOT NULL UNIQUE,
  patient_id     integer NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
  appointment_id integer REFERENCES appointments(id) ON DELETE SET NULL,
  issued_on      text NOT NULL,
  due_on         text NOT NULL DEFAULT '',
  status         text NOT NULL DEFAULT 'unpaid',
  subtotal_cents integer NOT NULL DEFAULT 0,
  tax_cents      integer NOT NULL DEFAULT 0,
  total_cents    integer NOT NULL DEFAULT 0,
  paid_cents     integer NOT NULL DEFAULT 0,
  notes          text NOT NULL DEFAULT ''
);

CREATE INDEX IF NOT EXISTS idx_inv_patient ON invoices(patient_id);
CREATE INDEX IF NOT EXISTS idx_inv_issued  ON invoices(issued_on);

-- Deferred: appointments is created before invoices exists.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'appointments_invoice_id_fkey'
  ) THEN
    ALTER TABLE appointments
      ADD CONSTRAINT appointments_invoice_id_fkey
      FOREIGN KEY (invoice_id) REFERENCES invoices(id) ON DELETE SET NULL;
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS invoice_items (
  id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invoice_id   integer NOT NULL REFERENCES invoices(id) ON DELETE CASCADE,
  kind         text NOT NULL DEFAULT 'treatment',
  description  text NOT NULL,
  quantity     integer NOT NULL DEFAULT 1,
  unit_cents   integer NOT NULL,
  tax_bps      integer NOT NULL DEFAULT 0,
  amount_cents integer NOT NULL,
  treatment_id integer REFERENCES treatments(id),
  product_id   integer REFERENCES products(id)
);

CREATE TABLE IF NOT EXISTS payments (
  id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invoice_id   integer NOT NULL REFERENCES invoices(id) ON DELETE CASCADE,
  patient_id   integer NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
  amount_cents integer NOT NULL,
  method       text NOT NULL DEFAULT 'card',
  reference    text NOT NULL DEFAULT '',
  received_on  text NOT NULL,
  note         text NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS claims (
  id             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invoice_id     integer NOT NULL REFERENCES invoices(id) ON DELETE CASCADE,
  patient_id     integer NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
  policy_id      integer REFERENCES insurance_policies(id) ON DELETE SET NULL,
  insurer_name   text NOT NULL,
  submitted_on   text NOT NULL DEFAULT '',
  responded_on   text NOT NULL DEFAULT '',
  status         text NOT NULL DEFAULT 'draft',
  billed_cents   integer NOT NULL DEFAULT 0,
  approved_cents integer NOT NULL DEFAULT 0,
  paid_cents     integer NOT NULL DEFAULT 0,
  adjudication   text NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS communications (
  id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id integer NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
  kind       text NOT NULL DEFAULT 'note',
  direction  text NOT NULL DEFAULT 'out',
  subject    text NOT NULL DEFAULT '',
  body       text NOT NULL DEFAULT '',
  author     text NOT NULL DEFAULT 'Front desk',
  created_at text NOT NULL
);

CREATE TABLE IF NOT EXISTS tasks (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title       text NOT NULL,
  detail      text NOT NULL DEFAULT '',
  due_on      text NOT NULL DEFAULT '',
  assignee_id integer REFERENCES practitioners(id) ON DELETE SET NULL,
  patient_id  integer REFERENCES patients(id) ON DELETE CASCADE,
  status      text NOT NULL DEFAULT 'open',
  created_at  text NOT NULL
);

CREATE TABLE IF NOT EXISTS audit_log (
  id        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  at        text NOT NULL,
  actor     text NOT NULL DEFAULT 'system',
  action    text NOT NULL,
  entity    text NOT NULL,
  entity_id integer,
  detail    text NOT NULL DEFAULT ''
);

-- Deny-by-default: Supabase publishes every public table over PostgREST.
-- With RLS on and no policies the anon key reads nothing; the app connects
-- as the table owner, which is exempt.
ALTER TABLE clinic ENABLE ROW LEVEL SECURITY;
ALTER TABLE locations ENABLE ROW LEVEL SECURITY;
ALTER TABLE disciplines ENABLE ROW LEVEL SECURITY;
ALTER TABLE practitioners ENABLE ROW LEVEL SECURITY;
ALTER TABLE availability ENABLE ROW LEVEL SECURITY;
ALTER TABLE treatments ENABLE ROW LEVEL SECURITY;
ALTER TABLE practitioner_treatments ENABLE ROW LEVEL SECURITY;
ALTER TABLE patients ENABLE ROW LEVEL SECURITY;
ALTER TABLE insurance_policies ENABLE ROW LEVEL SECURITY;
ALTER TABLE appointments ENABLE ROW LEVEL SECURITY;
ALTER TABLE chart_templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE chart_notes ENABLE ROW LEVEL SECURITY;
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE invoices ENABLE ROW LEVEL SECURITY;
ALTER TABLE invoice_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE claims ENABLE ROW LEVEL SECURITY;
ALTER TABLE communications ENABLE ROW LEVEL SECURITY;
ALTER TABLE tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_log ENABLE ROW LEVEL SECURITY;
